name: Deploy Medusa App to ECS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t swapnaswapna/medusa-app-docker/medusa-app:latest .

      # Step 4: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push swapnaswapna/medusa-app-docker:latest

      # Step 5: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Update with your region

      # Step 6: Deploy to ECS
      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          cluster: your-ecs-cluster-name
          service: your-ecs-service-name
          task-definition: your-task-definition.json
          container-name: medusa-container
          image: swapnaswapna/medusa-app-docker:latest
